import { useMemo, useState } from 'react'
import { ArrowRight, Compass, MapPin, Search, SlidersHorizontal, Sparkles } from 'lucide-react'
import EventCard, { Event } from '../components/EventCard'

const EVENTS: Event[] = [
  { id: 1, slug: 'the-sunday-reset', title: 'The Sunday Reset', date: 'Sun, 16 Jun', time: '10:00 AM', location: 'The Garden Room', city: 'Dublin', category: 'Wellness', price: '€18', image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=1200&q=85', description: 'A soft landing into the week ahead. Movement, good food, and the kind of conversations that stay with you.', organizer: 'Sunday Society', attendees: '84 going' },
  { id: 2, slug: 'late-night-radio', title: 'Late Night Radio', date: 'Fri, 21 Jun', time: '8:00 PM', location: 'The Sound House', city: 'Dublin', category: 'Music', price: '€12', image: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=85', organizer: 'NTS Dublin', attendees: '126 going' },
  { id: 3, slug: 'ceramics-and-chaos', title: 'Ceramics & Chaos', date: 'Sat, 22 Jun', time: '2:00 PM', location: 'Chancery Studio', city: 'Dublin', category: 'Creative', price: '€35', image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=900&q=85', organizer: 'Make Good Club', attendees: '32 going' },
  { id: 4, slug: 'rooftop-supper-club', title: 'Rooftop Supper Club', date: 'Sat, 22 Jun', time: '7:30 PM', location: 'The Dean Rooftop', city: 'Dublin', category: 'Food & drink', price: '€64', image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=900&q=85', organizer: 'Long Table', attendees: '47 going' },
  { id: 5, slug: 'soft-launch', title: 'Soft Launch', date: 'Thu, 27 Jun', time: '6:00 PM', location: 'The Library Project', city: 'Dublin', category: 'Community', price: 'Free', image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=85', organizer: 'SPOTevnt', attendees: '68 going' },
  { id: 6, slug: 'open-decks-at-the-bernard', title: 'Open Decks at The Bernard', date: 'Fri, 28 Jun', time: '9:00 PM', location: 'The Bernard Shaw', city: 'Dublin', category: 'Music', price: '€10', image: 'https://images.unsplash.com/photo-1571266028243-d220c9c3b21b?auto=format&fit=crop&w=900&q=85', organizer: 'Side B', attendees: '91 going' },
]
const CATEGORIES = ['All events', 'Music', 'Wellness', 'Creative', 'Food & drink', 'Community']

export default function DiscoveryFeed() {
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('All events')
  const [showFilters, setShowFilters] = useState(false)
  const filtered = useMemo(() => EVENTS.filter((event) => (category === 'All events' || event.category === category) && `${event.title} ${event.location}`.toLowerCase().includes(search.toLowerCase())), [category, search])
  return <div>
    <section className="grain overflow-hidden bg-spot-ink text-white"><div className="container-page relative py-20 sm:py-28"><div className="pointer-events-none absolute -right-20 -top-20 h-72 w-72 rounded-full bg-spot-blue/35 blur-3xl" /><div className="relative max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.16em] text-spot-lime"><Sparkles size={13} /> Your next good night</div><h1 className="font-display text-5xl font-bold leading-[0.95] tracking-[-0.07em] sm:text-7xl">Find something<br /><span className="text-spot-lime">worth showing up for.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/55 sm:text-lg">Small rooms, big feelings, and everything in between. Discover the moments that make a city feel like yours.</p></div><div className="relative mt-10 flex max-w-3xl flex-col gap-3 rounded-[20px] bg-white p-2 sm:flex-row"><label className="flex flex-1 items-center gap-3 rounded-2xl px-4 py-2 text-spot-ink"><Search className="text-spot-mist" size={20} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search events, places, or vibes" className="w-full bg-transparent text-sm outline-none placeholder:text-spot-mist" /></label><button className="btn-primary sm:px-7">Explore events <ArrowRight size={17} /></button></div></div></section>
    <section className="container-page py-14 sm:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Curated for you</p><h2 className="mt-2 font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">What’s happening</h2></div><button onClick={() => setShowFilters(!showFilters)} className="btn-outline self-start sm:self-auto"><SlidersHorizontal size={16} /> Filters</button></div><div className={`${showFilters ? 'flex' : 'hidden'} mt-8 flex-wrap gap-2 sm:flex`}><div className="mr-3 flex items-center gap-2 text-sm font-semibold"><MapPin size={15} className="text-spot-blue" /> Dublin</div>{CATEGORIES.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${category === item ? 'bg-spot-ink text-white' : 'bg-white text-spot-ink/60 hover:text-spot-ink'}`}>{item}</button>)}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((event, index) => <EventCard key={event.id} event={event} featured={index === 0} />)}</div>{filtered.length === 0 && <div className="rounded-3xl bg-white p-12 text-center"><Compass className="mx-auto text-spot-blue" /><h3 className="mt-4 font-display text-2xl font-bold">No events in that pocket yet</h3><p className="mt-2 text-sm text-spot-ink/55">Try another search or clear your filters.</p></div>}<div className="mt-14 flex justify-center"><button className="btn-outline">Load more events <ArrowRight size={16} /></button></div></section>
    <section className="bg-spot-lime"><div className="container-page flex flex-col justify-between gap-8 py-14 sm:flex-row sm:items-center sm:py-16"><div><p className="eyebrow text-spot-ink/45">Have a good thing going?</p><h2 className="mt-2 max-w-lg font-display text-3xl font-bold leading-tight tracking-[-0.05em] sm:text-4xl">Put it on the calendar. Bring your people.</h2></div><a href="/studio/create/" className="btn-dark shrink-0">Create an event <ArrowRight size={16} /></a></div></section>
  </div>
}
